openapi: 3.0.0
info:
  title: dtlab ingest alligator
  version: '1.0'
  contact:
    name: navicore
    email: ed@onextent.com
  license:
    name: MIT
    url: 'https://github.com/SoMind/dtlab-ingest-scala-alligator/blob/master/LICENSE'
  description: |-
    Manage DtLab Telemetry Ingest Service.

    DtLab Ingest is an streaming service that feeds the DtLab actor system updates from the field.
servers:
  - url: 'http://localhost:8082'
    description: dev local mode
paths:
  '/dtlab-ingest-alligator/extractor/telemetry/{specId}':
    parameters:
      - schema:
          type: string
        name: specId
        in: path
        required: true
    post:
      summary: create telemetry extraction spec
      tags:
        - tell
      responses:
        '201':
          description: A copy of the successfully created spec definition.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TelemetryExtractorSpec'
              examples:
                example-1:
                  value:
                    children:
                      - alternator_module
                      - starter_module
                    created: '2020-07-26T18:09:06.592Z'
                    name: machinery66
                    props:
                      - temp
                      - speed
        '401':
          description: Unauthorized
        '409':
          description: Conflict - you must delete the previous entry before creating a type of the same name.
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: post-dtlab-alligator-extractor-telemetry-specId
      description: Create a new spec with that defines how to identifiy the actors to update and the telemetry to extract.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TelemetryExtractorSpec'
            examples:
              example-1:
                value:
                  props:
                    - temp
                    - speed
                  children:
                    - alternator_module
                    - starter_module
        description: The array of telemetry extraction specs associated with this specId.
    get:
      summary: get telemetry extraction spec
      tags:
        - ask
      responses:
        '200':
          description: Definition of the type
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TelemetryExtractorSpec'
              examples:
                example-1:
                  value:
                    - specId: neo1
                      created: '2020-08-23T21:39:14.291Z'
                      datetimeFmt: 'yyyy-MMM-dd hh:mm'
                      datetimePath: '$.close_approach_data[0].close_approach_date_full'
                      paths:
                        - - name: orbiting_body
                            path: '$.close_approach_data[0].orbiting_body'
                            valueType: String
                          - name: object
                            path: $.neo_reference_id
                            valueType: String
                      values:
                        - idx: 0
                          path: $.absolute_magnitude_h
                          valueType: Double
                        - idx: 1
                          path: $.estimated_diameter.meters.estimated_diameter_min
                          valueType: Double
                        - idx: 2
                          path: $.estimated_diameter.meters.estimated_diameter_max
                          valueType: Double
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '':
          description: ''
      operationId: get-dtlab-alligator-extractor-telemetry-specId
      description: Look up a telemetry extraction spec by ID.
    delete:
      summary: delete telemetry extraction spec
      operationId: delete-dtlab-alligator-extractor-telemetry-specId
      responses:
        '202':
          description: Accepted
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      description: Delete the specId.
components:
  schemas:
    TelemetryExtractorSpec:
      title: TelemetryExtractorSpec
      type: object
      x-examples:
        example-1: {}
      properties:
        specId:
          type: string
        paths:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/PathSpec'
        values:
          type: array
          items:
            $ref: '#/components/schemas/ValueSpec'
        datetimePath:
          type: string
        datetimeFmt:
          type: string
        created:
          type: string
    PathSpec:
      title: PathSpec
      type: object
      properties:
        name:
          type: string
        path:
          type: string
        valueType:
          type: string
    ValueSpec:
      title: ValueSpec
      type: object
      properties:
        idx:
          type: integer
        path:
          type: string
        valueSpec:
          type: string
    ObjectExtractorSpec:
      title: ObjectExtractorSpec
      type: object
      properties:
        specId:
          type: string
        path:
          type: string
        telSpecId:
          type: string
        created:
          type: string
    Telemetry:
      title: Telemetry
      type: object
      properties:
        idx:
          type: string
        value:
          type: number
        datetime:
          type: string
tags:
  - name: create
  - name: delete
  - name: ask
  - name: tell
