http://localhost:8082

Content-Type: application/json; charset=utf-8

--

--
GET /dtlab-alligator/extractor/telemetry/wh_sc

--
DELETE /dtlab-alligator/extractor/telemetry/wh_sc
--
POST /dtlab-alligator/extractor/telemetry/wh_sc
[{
  "paths": [[
    {
      "name": "wh_monitor",
      "path": "$.event",
      "valueType": "String"
    }
  ]],
  "values": [
    {
      "typeId": "wh_monitor",
      "name": "count",
      "path": 1.0,
      "valueType": "Double"
    }
  ],
  "datetimePath": "$.created",
  "datetimeFmt": "yyyy-MMM-dd hh:mm"

}]

--
GET /fitness

--
GET /observe
