http://localhost:8082

Content-Type: application/json; charset=utf-8

--

--
GET /dtlab-alligator/extractor/telemetry/fleetmgrss

--
DELETE /dtlab-alligator/extractor/telemetry/fleetmgrss
--
POST /dtlab-alligator/extractor/telemetry/fleetmgrss
[{
  "paths": [[
    {
      "name": "wh_monitor",
      "path": "$.eventType",
      "valueType": "String"
    }
  ]],
  "values": [
    {
      "typeId": "wh_monitor",
      "name": "count",
      "path": "1.0",
      "valueType": "Literal"
    }
  ],
  "datetimePath": "$.created",
  "datetimeFmt": "yyyy-MM-dd'T'HH:mm:ss.SSSX"

}]

--
GET /fitness

--
GET /observe
