http://localhost:8082
#https://somind.tech
#https://somind.org

Content-Type: application/json; charset=utf-8

--

--
GET /dtlab-alligator/extractor/object/neo1

--
DELETE /dtlab-alligator/extractor/object/neo1

--
POST /dtlab-alligator/extractor/object/neo1
{
  "path": "$.near_earth_objects.*.*",
  "destUrl": "/dtlab-alligator/ingest/object/neo1"
}

--
GET /fitness

--
GET /observe

