http://localhost:8082

Content-Type: application/json; charset=utf-8

--

--
GET /dtlab-alligator/extractor/telemetry/neo1

--
DELETE /dtlab-alligator/extractor/telemetry/neo1

--
POST /dtlab-alligator/extractor/telemetry/neo1
[{
  "paths": [[
    {
      "name": "orbiting_body",
      "path": "$.close_approach_data[0].orbiting_body",
      "valueType": "String"
    },
    {
      "name": "object",
      "path": "$.neo_reference_id",
      "valueType": "String"
    }
  ]],
  "values": [
    {
      "idx": 0,
      "path": "$.absolute_magnitude_h",
      "valueType": "Double"
    },
    {
      "idx": 1,
      "path": "$.estimated_diameter.meters.estimated_diameter_min",
      "valueType": "Double"
    },
    {
      "idx": 2,
      "path": "$.estimated_diameter.meters.estimated_diameter_max",
      "valueType": "Double"
    }
  ],
  "datetimePath": "$.close_approach_data[0].close_approach_date_full",
  "datetimeFmt": "yyyy-MMM-dd hh:mm"

}]

--
GET /fitness

--
GET /observe

