http://localhost:8082
#https://somind.tech
#https://somind.org

Content-Type: application/json; charset=utf-8

--

--
GET /dtlab-alligator/extractor/telemetry/neo1

--
DELETE /dtlab-alligator/extractor/telemetry/neo1

--
POST /dtlab-alligator/extractor/telemetry/neo1
[{
  "paths": [[
    {
      "name": "orbiting_body",
      "path": "$.close_approach_data[0].orbiting_body",
      "valueType": "String"
    },
    {
      "name": "object",
      "path": "$.neo_reference_id",
      "valueType": "String"
    }
  ]],
  "values": [
    {
      "idx": 0,
      "path": "$.estimated_diameter.meters.estimated_diameter_min",
      "valueType": "Double"
    },
    {
      "idx": 1,
      "path": "$.estimated_diameter.meters.estimated_diameter_max",
      "valueType": "Double"
    }
  ]
}]

--
GET /fitness

--
GET /observe

